meta_product_name: "HERO"
meta_title: "HERO - Send requests easily"
meta_description: "With HERO, you can easily send requests to your office manager from Slack"
meta_image: "card_social_media.png" # should exist in `app/assets/images/`
twitter_account: "@HERO70772975"   # required for Twitter Cards
